name: aclimatise-test
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7.5
  - bwa==0.7.17
  - samtools=1.7
  - bedtools==2.26.0
  - htseq==0.12.4
  - dinosaur==1.1.3
  - pisces==5.2.9.122
  - openssl==1.0
