name:

on: [push]

jobs:
  conda:
    # Run tests using conda, which gives us bioinformatics tools installed
    runs-on: ubuntu-latest
    container: continuumio/miniconda3
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          source /root/.bashrc
          conda env create -f environment.yml
          conda activate aclimatise-test
          pip install --upgrade pip wheel setuptools
          pip install -e .[dev]
          pytest
        shell: bash

  system python:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip wheel setuptools
          pip install -e .[dev]

      - uses: pre-commit/action@v1.0.1

      - name: Test with pytest
        run: |
          pytest

  publish:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Compile package
        run: |
          pip install -U wheel setuptools
          python setup.py sdist bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
